# Generated by Django 2.2.4 on 2019-08-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190828_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='num',
        ),
        migrations.AddField(
            model_name='solution',
            name='number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
