# Generated by Django 2.2.4 on 2019-08-30 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='author',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
